name: Spellcheck Action
on: push

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.11.0
      name: Spellcheck
      with:
        config_path: .spellcheck/spellcheck.yml
        task_name: Markdown
